// Copyright 2026 landon-lockhart. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types


type SiteGetNbaScoreboardResponse struct {
}

type SiteGetNbaSummaryResponse struct {
}

type SiteGetNcaabScoreboardResponse struct {
}

type SiteGetNcaabSummaryResponse struct {
}

type SiteGetNcaafScoreboardResponse struct {
}

type SiteGetNcaafSummaryResponse struct {
}

type SiteGetNflScoreboardResponse struct {
}

type SiteGetNflSummaryResponse struct {
}
