// Copyright 2026 landon-lockhart. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSiteCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "site",
		Short: "Manage site",
	}

	cmd.AddCommand(newSiteGetNbaScoreboardCmd(flags))
	cmd.AddCommand(newSiteGetNbaSummaryCmd(flags))
	cmd.AddCommand(newSiteGetNcaabScoreboardCmd(flags))
	cmd.AddCommand(newSiteGetNcaabSummaryCmd(flags))
	cmd.AddCommand(newSiteGetNcaafScoreboardCmd(flags))
	cmd.AddCommand(newSiteGetNcaafSummaryCmd(flags))
	cmd.AddCommand(newSiteGetNflScoreboardCmd(flags))
	cmd.AddCommand(newSiteGetNflSummaryCmd(flags))
	cmd.AddCommand(newSiteGetMlbScoreboardCmd(flags))
	cmd.AddCommand(newSiteGetMlbSummaryCmd(flags))
	return cmd
}
