// Copyright 2026 landon-lockhart. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSiteGetMlbSummaryCmd(flags *rootFlags) *cobra.Command {
	var flagEvent string

	cmd := &cobra.Command{
		Use:         "get-mlb-summary",
		Short:       "Return an MLB game's summary and box score from ESPN.",
		Example:     "  espn-sports-pp-cli site get-mlb-summary --event example-value",
		Annotations: map[string]string{"pp:endpoint": "site.get-mlb-summary", "pp:method": "GET", "pp:path": "/apis/site/v2/sports/baseball/mlb/summary", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("event") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "event")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/apis/site/v2/sports/baseball/mlb/summary"
			params := map[string]string{}
			if flagEvent != "" {
				params["event"] = fmt.Sprintf("%v", flagEvent)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "site", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			scoreline := map[string]any(nil)
			if flagEvent != "" {
				scoreClient := *c
				scoreClient.NoCache = true
				if scoreboard, scoreErr := scoreClient.Get("/apis/site/v2/sports/baseball/mlb/scoreboard", nil); scoreErr == nil {
					scoreline, _ = extractScorelineFromScoreboard(scoreboard, flagEvent)
				}
			}
			if scoreline == nil {
				scoreline, _ = extractScoreline(data)
			}
			if scoreline != nil && isTerminal(cmd.OutOrStdout()) {
				fmt.Fprintln(cmd.ErrOrStderr(), scoreline["display"])
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenanceAndExtras(filtered, prov, map[string]any{"scoreline": scoreline})
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagEvent, "event", "", "ESPN event id from the MLB scoreboard payload.")

	return cmd
}
